name: page-deploy
on:
  workflow_dispatch:
  repository_dispatch:
    types: theme_commit
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: init_hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.88.1'
          extended: true
      - name: set_up_hugo_site
        run: |
          hugo new site ./blog111
          mkdir ./blog111/themes/hugo-theme-stack
          git clone https://github.com/Nixum/hugo-theme-stack.git ./blog111/themes/hugo-theme-stack
          echo "---"
          cat ./blog111/themes/hugo-theme-stack/layouts/_default/single.html
          echo "---"
          rm ./blog111/config.toml
          cp ./blog111/themes/hugo-theme-stack/config.yaml ./blog111/config.yaml
          cp -r ./blog111/themes/hugo-theme-stack/custom-content/* ./blog111/content/
      - name: Build
        run: |
          mkdir ./blog111/content/post
          cp *.md ./blog111/content/post/
          cd blog111
          hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: Nixum/blog
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./blog111/public
